### ISSUE TITLE
How to recirculate packets?

### ISSUE THREAD

**Issue by AnotherKamila** [NetFPGA/P4-NetFPGA-public#6]
Hello,

am I right to think that the SimpleSumeSwitch architecture does not support recirculating packets? If that is the case, how can it be added? Do I need to create a custom architecture for that? If yes, do you have any idea about when the documentation/tools mentioned in #4 might be released?

Also, if I wanted to use the SDNet's `packet_mod` feature, would I need a custom architecture for that as well?

Thank you!

**Comment by sibanez12** [comment]
Hi Kamila,

That's correct, the SimpleSumeSwitch does not support recirculating packets. If you want to add support for it you'll need to change some HDL files, mainly the [nf_sume_sdnet wrapper module](https://github.com/NetFPGA/P4-NetFPGA-live/blob/master/contrib-projects/sume-sdnet-switch/templates/sss_wrapper/hdl/nf_sume_sdnet.v) and the [input_arbiter](https://github.com/NetFPGA/P4-NetFPGA-live/blob/master/lib/hw/std/cores/input_arbiter_v1_0_0/hdl/input_arbiter.v) so that they support the extra recirculation path.

Regarding the `packet_mod` and PTA tool, see [NetFPGA/P4-NetFPGA-live#13](https://github.com/NetFPGA/P4-NetFPGA-live/issues/13).

**Comment by AnotherKamila** [comment]
Thank you very much! I think I'll first try the `packet_mod` if I manage to make it work, but having this option as a backup plan is great.

I really appreciate your help! It's really useful for me to be pointed to the right things.
