### ISSUE TITLE
Cannot Push Bitfiles into NetFPgA SUME - No such device!!!

### ISSUE THREAD

**Issue by mharris-t** [NetFPGA/P4-NetFPGA-public#62]
Hi,

**System specs:**

Motherboard: Fujitsu D3227-A1
CPU: Intel(R) Xeon(R) CPU E3-1230 v3 @ 3.30GHz

**Operating System:**

Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

**Vivado Version:** 2018.2
**SDNet Version:** 2018.2

I am having issues with pushing bitfiles into the netfpga. Moreover, I am having trouble in detecting the interfaces nf0, nf1, nf2 and nf3. However, my ~~motherboard~~ usb serial connection has been able to detect the netfpga and I have been able to connect to the board with USB over minicom. 

![image](https://user-images.githubusercontent.com/60294955/113990825-87567180-985a-11eb-93d9-445af6960dc4.png)

![image](https://user-images.githubusercontent.com/60294955/113992341-06987500-985c-11eb-9d55-037ffbf7c96c.png)

I have rebooted my system several times. Restarted my networking services.  Reinstalled and loaded **sume_riffa** drivers. But these don't seem to work. The _**lspci**_ command does not display the netfpga in the results. But **_djtgcfg enum_** command shows the detected NIC in the system. Also, Vivado's Hardware Manager detects the Xilinx chipset. 

![image](https://user-images.githubusercontent.com/60294955/113991364-0c418b00-985b-11eb-8fa1-d76aedb460c0.png)

![image](https://user-images.githubusercontent.com/60294955/113991078-c684c280-985a-11eb-89eb-fbcaba420a8d.png)

![image](https://user-images.githubusercontent.com/60294955/113991703-63dff680-985b-11eb-93d0-453372f04ebe.png)

**Comment by aomtoku** [comment]
13 of https://github.com/NetFPGA/P4-NetFPGA-public/wiki/Tutorial-Assignments#what-to-do would be helpful for you.

**Comment by mharris-t** [comment]
@aomtoku, I am stuck at exactly that point at step 13. When I try running running the bash script **program_switch.sh,** this is what happens:

![image](https://user-images.githubusercontent.com/60294955/113997705-11a1d400-9861-11eb-8bea-78d9cdf3ec67.png)


sume_riffa driver is loaded using modprobe, but the netfpga interfaces do not appear even after restarting the interfaces configuration in /etc/network/interfaces.

**Comment by aomtoku** [comment]
did you do this  of 13? 

##############################################################################
Note: Make sure that all the configuration writes succeed. If this is the first time you are programming the FPGA since the machine was last powered off then you might get ERROR messages stating No such device.

To resolve this, follow the below-mentioned steps:

a. Reboot the Machine

b. Execute the following commands (taken from Step 9 on Getting Started Page in this repo):

[root@nf-test109 ~]# cd $DRIVER_FOLDER

[root@nf-test109 sume_riffa_v1_0_0]# make all

[root@nf-test109 sume_riffa_v1_0_0]# make install

[root@nf-test109 sume_riffa_v1_0_0]# modprobe sume_riffa

[root@nf-test109 sume_riffa_v1_0_0]# lsmod | grep sume_riffa

c. Now, you will be able to see nf0, nf1, nf2 and nf3 ports in your ifconfig output. Re-execute the aforementioned commands in Step 13. This time the configuration writes & the loading bitstream process should succeed.

**Comment by mharris-t** [comment]
Yes, I have rebooted my machine several times and loaded the sume_riffa drivers. Even then, the interfaces do not appear unfortunately.

**Comment by aomtoku** [comment]
What is the result of lspci for sume?

**Comment by mharris-t** [comment]
Neither Xilinx nor sume gets detected in lspci. But I have been able to test the sume nic using minicom and it is detected in Vivado's hardware manager. 

![image](https://user-images.githubusercontent.com/60294955/114000063-50388e00-9863-11eb-843e-18d0211dc22b.png)

![image](https://user-images.githubusercontent.com/60294955/114000248-7e1dd280-9863-11eb-9c1a-79f8e4c22618.png)

**Comment by aomtoku** [comment]
I would suggest 
1) check PCIe connectivity 
2) check writing bitifile

**Comment by mharris-t** [comment]
Alright, it seems like my NIC isn't being detected in the PCIe slot. I will see what I can do. Could be a loose connection or the NIC is incompatible with my motherboard. Thank you very much!

**Comment by MyLifeForViolet** [comment]
# @mharris-t I meet the same problem with you.Have you ever solved this? I have tried all solutions mentioned above,unfortunately failed.

**Comment by MyLifeForViolet** [comment]
@mharris-t  Hi.I meet the same problem with you.Have you ever solved this? I have tried all solutions mentioned above,unfortunately failed.
